# Camera params
color_resolution: [1920, 1080]
depth_resolution: [1280, 720]
frames_per_second: 30
id: '821212060746'

# Chessboard params
chessboard_height: 14
chessboard_width: 9
chessboard_size: 17.4

# Ball params
ball_radius: 100